CREATE TABLE IF NOT EXISTS auction_items (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title TEXT NOT NULL,
  year SMALLINT UNSIGNED NOT NULL,
  make VARCHAR(120) NOT NULL,
  model VARCHAR(120) NOT NULL,
  category ENUM('Cars', 'Trucks', 'SUVs') NOT NULL,
  miles VARCHAR(80) NOT NULL,
  lane VARCHAR(40) NOT NULL,
  lot VARCHAR(40) NOT NULL UNIQUE,
  main_price INT UNSIGNED NOT NULL,
  discount_percent TINYINT UNSIGNED NOT NULL DEFAULT 60,
  vin VARCHAR(80) NOT NULL,
  title_status VARCHAR(120) NOT NULL,
  item_status VARCHAR(120) NOT NULL,
  seller VARCHAR(160) NOT NULL,
  light VARCHAR(80) NOT NULL,
  transmission VARCHAR(80) NOT NULL,
  drivetrain VARCHAR(80) NOT NULL,
  notes TEXT NOT NULL,
  image_url VARCHAR(500) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT chk_auction_discount_percent CHECK (discount_percent <= 100),
  INDEX idx_auction_items_category (category),
  INDEX idx_auction_items_active (is_active)
);
