INSERT INTO auction_items (
  title,
  year,
  make,
  model,
  category,
  miles,
  lane,
  lot,
  main_price,
  discount_percent,
  vin,
  title_status,
  item_status,
  seller,
  light,
  transmission,
  drivetrain,
  notes,
  image_url,
  is_active
) VALUES
(
  '2022 Lamborghini Urus',
  2022,
  'Lamborghini',
  'Urus',
  'SUVs',
  '18k mi',
  'L01',
  '2201',
  268000.00,
  60.00,
  'ZPBUA1ZL***2201',
  'Clean title',
  'Green light',
  'Luxury dealer consignment',
  'Green light',
  'Automatic',
  'AWD',
  'Black exotic SUV, panoramic roof, carbon interior package, performance exhaust, documented service history.',
  '/uploads/auction-items/seed-vehicle-lamborghini-urus.png',
  1
),
(
  '2021 Mercedes-Benz G 63 AMG',
  2021,
  'Mercedes-Benz',
  'G 63 AMG',
  'SUVs',
  '24k mi',
  'L02',
  '2202',
  214000.00,
  60.00,
  'W1NYC7HJ***2202',
  'Clean title',
  'Green light',
  'Dealer consignment',
  'Green light',
  'Automatic',
  'AWD',
  'White G-Class, AMG trim, black wheels, premium leather cabin, verified keys and documents.',
  '/uploads/auction-items/seed-vehicle-mercedes-g63.png',
  1
),
(
  '2023 Rolls-Royce Cullinan',
  2023,
  'Rolls-Royce',
  'Cullinan',
  'SUVs',
  '9k mi',
  'L03',
  '2203',
  392000.00,
  60.00,
  'SCA689X5***2203',
  'Clean title',
  'Luxury consignment',
  'Private seller',
  'Green light',
  'Automatic',
  'AWD',
  'Silver ultra-luxury SUV, rear comfort package, premium audio, soft-close doors, sale packet verified.',
  '/uploads/auction-items/seed-vehicle-rolls-royce-cullinan.png',
  1
),
(
  '2022 Ferrari Roma',
  2022,
  'Ferrari',
  'Roma',
  'Cars',
  '12k mi',
  'L04',
  '2204',
  248000.00,
  60.00,
  'ZFF98RNA***2204',
  'Clean title',
  'Green light',
  'Luxury dealer consignment',
  'Green light',
  'Automatic',
  'RWD',
  'Red grand touring coupe, carbon steering wheel, upgraded wheels, clean history, title on site.',
  '/uploads/auction-items/seed-vehicle-ferrari-roma.png',
  1
)
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  year = VALUES(year),
  make = VALUES(make),
  model = VALUES(model),
  category = VALUES(category),
  miles = VALUES(miles),
  lane = VALUES(lane),
  main_price = VALUES(main_price),
  discount_percent = VALUES(discount_percent),
  vin = VALUES(vin),
  title_status = VALUES(title_status),
  item_status = VALUES(item_status),
  seller = VALUES(seller),
  light = VALUES(light),
  transmission = VALUES(transmission),
  drivetrain = VALUES(drivetrain),
  notes = VALUES(notes),
  image_url = VALUES(image_url),
  is_active = VALUES(is_active);
