INSERT INTO auction_items (
  title,
  year,
  make,
  model,
  category,
  miles,
  lane,
  lot,
  main_price,
  discount_percent,
  vin,
  title_status,
  item_status,
  seller,
  light,
  transmission,
  drivetrain,
  notes,
  image_url
) VALUES
(
  '2021 Toyota Camry SE',
  2021,
  'Toyota',
  'Camry SE',
  'Cars',
  '48k mi',
  'A12',
  '1021',
  28900,
  60,
  '4T1G11AK***2184',
  'Clean title',
  'Runs & drives',
  'New car trade',
  'Green light',
  'Automatic',
  'FWD',
  'Clean interior, cold air, alloy wheels, sale-ready sedan.',
  '/uploads/auction-items/seed-vehicle-camry.png'
),
(
  '2020 Ford F-150 XLT',
  2020,
  'Ford',
  'F-150 XLT',
  'Trucks',
  '72k mi',
  'B03',
  '1044',
  36500,
  60,
  '1FTEW1E5***7731',
  'Title present',
  'Fleet seller',
  'Fleet account',
  'Green light',
  'Automatic',
  '4x4',
  'Crew cab, bed liner, tow package, strong fleet maintenance history.',
  '/uploads/auction-items/seed-vehicle-f150.png'
),
(
  '2019 Honda CR-V EX',
  2019,
  'Honda',
  'CR-V EX',
  'SUVs',
  '61k mi',
  'A28',
  '1088',
  31200,
  60,
  '2HKRW2H5***9036',
  'Clean title',
  'Public consignment',
  'Public seller',
  'Yellow light',
  'CVT',
  'AWD',
  'Sunroof, backup camera, newer tires, title verified at intake.',
  '/uploads/auction-items/seed-vehicle-crv.png'
),
(
  '2018 Chevrolet Silverado LT',
  2018,
  'Chevrolet',
  'Silverado LT',
  'Trucks',
  '89k mi',
  'C14',
  '1136',
  34800,
  60,
  '3GCUKREC***5120',
  'Title absent',
  'Green light',
  'Dealer consignment',
  'Green light',
  'Automatic',
  '4x4',
  'Crew cab, chrome package, clean body, title pending from seller.',
  '/uploads/auction-items/seed-vehicle-silverado.png'
);
